apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: video-request-manager
spec:
  virtualhost:
    fqdn: vrm.example.com
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: video-request-manager-admin
spec:
  virtualhost:
    fqdn: admin.vrm.example.com
