apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: video-request-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/glauciolabs/video-request-manager-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: vrm-config
            - secretRef:
                name: vrm-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: video-request-manager
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
