apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - base/secret.template.yaml
  - frontend/frontend.yaml
  - frontend/admin-frontend.yaml
  - gateway/api-gateway.yaml
  - services/order-service.yaml
  - services/user-service.yaml
  - services/notification-service.yaml
  - services/sla-service.yaml
  - services/report-service.yaml
  - db/cloudnative-pg-secret.yaml
  - db/cloudnative-pg-cluster.yaml
  - cronjob/db-backup-cronjob.yaml
  - ingress/ingress.yaml
  - gatewayapi/gateway.yaml
  - gatewayapi/http-route.yaml
