apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: video-request-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/glauciolabs/video-request-manager-user-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
          envFrom:
            - configMapRef:
                name: vrm-config
            - secretRef:
                name: vrm-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: video-request-manager
spec:
  selector:
    app: user-service
  ports:
    - port: 3002
      targetPort: 3002
