apiVersion: v1
kind: ConfigMap
metadata:
  name: vrm-config
data:
  NEXT_PUBLIC_API_BASE_URL: "https://vrm-dev.glauciolabs.work/api"
  TRACKING_BASE_URL: "https://vrm-dev.glauciolabs.work/tracking"
  CORS_ALLOWED_ORIGINS: "https://vrm-dev.glauciolabs.work,https://admin-vrm-dev.glauciolabs.work"
